/* ============================================================
   Samurai Sam — dati statici (kana, kanji, vocabolario, frasi)
   Modifica/aggiungi voci qui: l'app le userà automaticamente.
   ============================================================ */

// ---------- HIRAGANA ----------
// lvl: 1 = base (46), 2 = dakuten/handakuten, 3 = combinazioni (youon)
var HIRAGANA = [
  {k:'あ',r:'a',lvl:1},{k:'い',r:'i',lvl:1},{k:'う',r:'u',lvl:1},{k:'え',r:'e',lvl:1},{k:'お',r:'o',lvl:1},
  {k:'か',r:'ka',lvl:1},{k:'き',r:'ki',lvl:1},{k:'く',r:'ku',lvl:1},{k:'け',r:'ke',lvl:1},{k:'こ',r:'ko',lvl:1},
  {k:'さ',r:'sa',lvl:1},{k:'し',r:'shi',lvl:1},{k:'す',r:'su',lvl:1},{k:'せ',r:'se',lvl:1},{k:'そ',r:'so',lvl:1},
  {k:'た',r:'ta',lvl:1},{k:'ち',r:'chi',lvl:1},{k:'つ',r:'tsu',lvl:1},{k:'て',r:'te',lvl:1},{k:'と',r:'to',lvl:1},
  {k:'な',r:'na',lvl:1},{k:'に',r:'ni',lvl:1},{k:'ぬ',r:'nu',lvl:1},{k:'ね',r:'ne',lvl:1},{k:'の',r:'no',lvl:1},
  {k:'は',r:'ha',lvl:1},{k:'ひ',r:'hi',lvl:1},{k:'ふ',r:'fu',lvl:1},{k:'へ',r:'he',lvl:1},{k:'ほ',r:'ho',lvl:1},
  {k:'ま',r:'ma',lvl:1},{k:'み',r:'mi',lvl:1},{k:'む',r:'mu',lvl:1},{k:'め',r:'me',lvl:1},{k:'も',r:'mo',lvl:1},
  {k:'や',r:'ya',lvl:1},{k:'ゆ',r:'yu',lvl:1},{k:'よ',r:'yo',lvl:1},
  {k:'ら',r:'ra',lvl:1},{k:'り',r:'ri',lvl:1},{k:'る',r:'ru',lvl:1},{k:'れ',r:'re',lvl:1},{k:'ろ',r:'ro',lvl:1},
  {k:'わ',r:'wa',lvl:1},{k:'を',r:'wo',lvl:1},{k:'ん',r:'n',lvl:1},
  {k:'が',r:'ga',lvl:2},{k:'ぎ',r:'gi',lvl:2},{k:'ぐ',r:'gu',lvl:2},{k:'げ',r:'ge',lvl:2},{k:'ご',r:'go',lvl:2},
  {k:'ざ',r:'za',lvl:2},{k:'じ',r:'ji',lvl:2},{k:'ず',r:'zu',lvl:2},{k:'ぜ',r:'ze',lvl:2},{k:'ぞ',r:'zo',lvl:2},
  {k:'だ',r:'da',lvl:2},{k:'ぢ',r:'ji',lvl:2},{k:'づ',r:'zu',lvl:2},{k:'で',r:'de',lvl:2},{k:'ど',r:'do',lvl:2},
  {k:'ば',r:'ba',lvl:2},{k:'び',r:'bi',lvl:2},{k:'ぶ',r:'bu',lvl:2},{k:'べ',r:'be',lvl:2},{k:'ぼ',r:'bo',lvl:2},
  {k:'ぱ',r:'pa',lvl:2},{k:'ぴ',r:'pi',lvl:2},{k:'ぷ',r:'pu',lvl:2},{k:'ぺ',r:'pe',lvl:2},{k:'ぽ',r:'po',lvl:2},
  {k:'きゃ',r:'kya',lvl:3},{k:'きゅ',r:'kyu',lvl:3},{k:'きょ',r:'kyo',lvl:3},
  {k:'しゃ',r:'sha',lvl:3},{k:'しゅ',r:'shu',lvl:3},{k:'しょ',r:'sho',lvl:3},
  {k:'ちゃ',r:'cha',lvl:3},{k:'ちゅ',r:'chu',lvl:3},{k:'ちょ',r:'cho',lvl:3},
  {k:'にゃ',r:'nya',lvl:3},{k:'にゅ',r:'nyu',lvl:3},{k:'にょ',r:'nyo',lvl:3},
  {k:'ひゃ',r:'hya',lvl:3},{k:'ひゅ',r:'hyu',lvl:3},{k:'ひょ',r:'hyo',lvl:3},
  {k:'みゃ',r:'mya',lvl:3},{k:'みゅ',r:'myu',lvl:3},{k:'みょ',r:'myo',lvl:3},
  {k:'りゃ',r:'rya',lvl:3},{k:'りゅ',r:'ryu',lvl:3},{k:'りょ',r:'ryo',lvl:3},
  {k:'ぎゃ',r:'gya',lvl:3},{k:'ぎゅ',r:'gyu',lvl:3},{k:'ぎょ',r:'gyo',lvl:3},
  {k:'じゃ',r:'ja',lvl:3},{k:'じゅ',r:'ju',lvl:3},{k:'じょ',r:'jo',lvl:3},
  {k:'びゃ',r:'bya',lvl:3},{k:'びゅ',r:'byu',lvl:3},{k:'びょ',r:'byo',lvl:3},
  {k:'ぴゃ',r:'pya',lvl:3},{k:'ぴゅ',r:'pyu',lvl:3},{k:'ぴょ',r:'pyo',lvl:3},
];

// ---------- KATAKANA ----------
var KATAKANA = [
  {k:'ア',r:'a',lvl:1},{k:'イ',r:'i',lvl:1},{k:'ウ',r:'u',lvl:1},{k:'エ',r:'e',lvl:1},{k:'オ',r:'o',lvl:1},
  {k:'カ',r:'ka',lvl:1},{k:'キ',r:'ki',lvl:1},{k:'ク',r:'ku',lvl:1},{k:'ケ',r:'ke',lvl:1},{k:'コ',r:'ko',lvl:1},
  {k:'サ',r:'sa',lvl:1},{k:'シ',r:'shi',lvl:1},{k:'ス',r:'su',lvl:1},{k:'セ',r:'se',lvl:1},{k:'ソ',r:'so',lvl:1},
  {k:'タ',r:'ta',lvl:1},{k:'チ',r:'chi',lvl:1},{k:'ツ',r:'tsu',lvl:1},{k:'テ',r:'te',lvl:1},{k:'ト',r:'to',lvl:1},
  {k:'ナ',r:'na',lvl:1},{k:'ニ',r:'ni',lvl:1},{k:'ヌ',r:'nu',lvl:1},{k:'ネ',r:'ne',lvl:1},{k:'ノ',r:'no',lvl:1},
  {k:'ハ',r:'ha',lvl:1},{k:'ヒ',r:'hi',lvl:1},{k:'フ',r:'fu',lvl:1},{k:'ヘ',r:'he',lvl:1},{k:'ホ',r:'ho',lvl:1},
  {k:'マ',r:'ma',lvl:1},{k:'ミ',r:'mi',lvl:1},{k:'ム',r:'mu',lvl:1},{k:'メ',r:'me',lvl:1},{k:'モ',r:'mo',lvl:1},
  {k:'ヤ',r:'ya',lvl:1},{k:'ユ',r:'yu',lvl:1},{k:'ヨ',r:'yo',lvl:1},
  {k:'ラ',r:'ra',lvl:1},{k:'リ',r:'ri',lvl:1},{k:'ル',r:'ru',lvl:1},{k:'レ',r:'re',lvl:1},{k:'ロ',r:'ro',lvl:1},
  {k:'ワ',r:'wa',lvl:1},{k:'ヲ',r:'wo',lvl:1},{k:'ン',r:'n',lvl:1},
  {k:'ガ',r:'ga',lvl:2},{k:'ギ',r:'gi',lvl:2},{k:'グ',r:'gu',lvl:2},{k:'ゲ',r:'ge',lvl:2},{k:'ゴ',r:'go',lvl:2},
  {k:'ザ',r:'za',lvl:2},{k:'ジ',r:'ji',lvl:2},{k:'ズ',r:'zu',lvl:2},{k:'ゼ',r:'ze',lvl:2},{k:'ゾ',r:'zo',lvl:2},
  {k:'ダ',r:'da',lvl:2},{k:'ヂ',r:'ji',lvl:2},{k:'ヅ',r:'zu',lvl:2},{k:'デ',r:'de',lvl:2},{k:'ド',r:'do',lvl:2},
  {k:'バ',r:'ba',lvl:2},{k:'ビ',r:'bi',lvl:2},{k:'ブ',r:'bu',lvl:2},{k:'ベ',r:'be',lvl:2},{k:'ボ',r:'bo',lvl:2},
  {k:'パ',r:'pa',lvl:2},{k:'ピ',r:'pi',lvl:2},{k:'プ',r:'pu',lvl:2},{k:'ペ',r:'pe',lvl:2},{k:'ポ',r:'po',lvl:2},
  {k:'キャ',r:'kya',lvl:3},{k:'キュ',r:'kyu',lvl:3},{k:'キョ',r:'kyo',lvl:3},
  {k:'シャ',r:'sha',lvl:3},{k:'シュ',r:'shu',lvl:3},{k:'ショ',r:'sho',lvl:3},
  {k:'チャ',r:'cha',lvl:3},{k:'チュ',r:'chu',lvl:3},{k:'チョ',r:'cho',lvl:3},
  {k:'ニャ',r:'nya',lvl:3},{k:'ニュ',r:'nyu',lvl:3},{k:'ニョ',r:'nyo',lvl:3},
  {k:'ヒャ',r:'hya',lvl:3},{k:'ヒュ',r:'hyu',lvl:3},{k:'ヒョ',r:'hyo',lvl:3},
  {k:'ミャ',r:'mya',lvl:3},{k:'ミュ',r:'myu',lvl:3},{k:'ミョ',r:'myo',lvl:3},
  {k:'リャ',r:'rya',lvl:3},{k:'リュ',r:'ryu',lvl:3},{k:'リョ',r:'ryo',lvl:3},
  {k:'ギャ',r:'gya',lvl:3},{k:'ギュ',r:'gyu',lvl:3},{k:'ギョ',r:'gyo',lvl:3},
  {k:'ジャ',r:'ja',lvl:3},{k:'ジュ',r:'ju',lvl:3},{k:'ジョ',r:'jo',lvl:3},
  {k:'ビャ',r:'bya',lvl:3},{k:'ビュ',r:'byu',lvl:3},{k:'ビョ',r:'byo',lvl:3},
  {k:'ピャ',r:'pya',lvl:3},{k:'ピュ',r:'pyu',lvl:3},{k:'ピョ',r:'pyo',lvl:3},
];

// ---------- KANJI DI BASE ----------
// grp: raggruppamento tematico per lo studio a blocchi
var KANJI_BASE = [
  // numeri
  {k:'一',r:'ichi',it:'uno (1)',grp:'numeri'},{k:'二',r:'ni',it:'due (2)',grp:'numeri'},
  {k:'三',r:'san',it:'tre (3)',grp:'numeri'},{k:'四',r:'yon',it:'quattro (4)',grp:'numeri'},
  {k:'五',r:'go',it:'cinque (5)',grp:'numeri'},{k:'六',r:'roku',it:'sei (6)',grp:'numeri'},
  {k:'七',r:'nana',it:'sette (7)',grp:'numeri'},{k:'八',r:'hachi',it:'otto (8)',grp:'numeri'},
  {k:'九',r:'kyuu',it:'nove (9)',grp:'numeri'},{k:'十',r:'juu',it:'dieci (10)',grp:'numeri'},
  {k:'百',r:'hyaku',it:'cento',grp:'numeri'},{k:'千',r:'sen',it:'mille',grp:'numeri'},{k:'万',r:'man',it:'diecimila',grp:'numeri'},
  // tempo
  {k:'日',r:'hi',it:'giorno / sole',grp:'tempo'},{k:'月',r:'tsuki',it:'luna / mese',grp:'tempo'},
  {k:'年',r:'toshi',it:'anno',grp:'tempo'},{k:'時',r:'ji',it:'ora',grp:'tempo'},
  {k:'分',r:'fun',it:'minuto',grp:'tempo'},{k:'今',r:'ima',it:'adesso',grp:'tempo'},{k:'週',r:'shuu',it:'settimana',grp:'tempo'},
  // natura
  {k:'山',r:'yama',it:'montagna',grp:'natura'},{k:'川',r:'kawa',it:'fiume',grp:'natura'},
  {k:'木',r:'ki',it:'albero',grp:'natura'},{k:'水',r:'mizu',it:'acqua',grp:'natura'},
  {k:'火',r:'hi',it:'fuoco',grp:'natura'},{k:'空',r:'sora',it:'cielo',grp:'natura'},
  {k:'雨',r:'ame',it:'pioggia',grp:'natura'},{k:'花',r:'hana',it:'fiore',grp:'natura'},
  {k:'海',r:'umi',it:'mare',grp:'natura'},{k:'石',r:'ishi',it:'pietra',grp:'natura'},
  // persone e corpo
  {k:'人',r:'hito',it:'persona',grp:'persone'},{k:'私',r:'watashi',it:'io',grp:'persone'},
  {k:'男',r:'otoko',it:'uomo',grp:'persone'},{k:'女',r:'onna',it:'donna',grp:'persone'},
  {k:'子',r:'ko',it:'bambino',grp:'persone'},{k:'手',r:'te',it:'mano',grp:'persone'},
  {k:'目',r:'me',it:'occhio',grp:'persone'},{k:'口',r:'kuchi',it:'bocca',grp:'persone'},
  {k:'心',r:'kokoro',it:'cuore / mente',grp:'persone'},{k:'力',r:'chikara',it:'forza',grp:'persone'},
  // luoghi e direzioni
  {k:'上',r:'ue',it:'sopra',grp:'luoghi'},{k:'下',r:'shita',it:'sotto',grp:'luoghi'},
  {k:'中',r:'naka',it:'dentro / centro',grp:'luoghi'},{k:'外',r:'soto',it:'fuori',grp:'luoghi'},
  {k:'前',r:'mae',it:'davanti',grp:'luoghi'},{k:'後',r:'ato',it:'dopo / dietro',grp:'luoghi'},
  {k:'右',r:'migi',it:'destra',grp:'luoghi'},{k:'左',r:'hidari',it:'sinistra',grp:'luoghi'},
  {k:'東',r:'higashi',it:'est',grp:'luoghi'},{k:'西',r:'nishi',it:'ovest',grp:'luoghi'},
  {k:'南',r:'minami',it:'sud',grp:'luoghi'},{k:'北',r:'kita',it:'nord',grp:'luoghi'},
  {k:'国',r:'kuni',it:'paese / nazione',grp:'luoghi'},{k:'家',r:'ie',it:'casa',grp:'luoghi'},
  // aggettivi e verbi radice
  {k:'大',r:'oo',it:'grande',grp:'aggettivi'},{k:'小',r:'chii',it:'piccolo',grp:'aggettivi'},
  {k:'高',r:'taka',it:'alto / caro',grp:'aggettivi'},{k:'新',r:'atara',it:'nuovo',grp:'aggettivi'},
  {k:'古',r:'furu',it:'vecchio',grp:'aggettivi'},{k:'長',r:'naga',it:'lungo',grp:'aggettivi'},
  {k:'早',r:'haya',it:'presto / veloce',grp:'aggettivi'},
  {k:'行',r:'i',it:'andare (radice)',grp:'verbi'},{k:'見',r:'mi',it:'vedere (radice)',grp:'verbi'},
  {k:'食',r:'ta',it:'mangiare (radice)',grp:'verbi'},{k:'飲',r:'no',it:'bere (radice)',grp:'verbi'},
  {k:'言',r:'i',it:'dire (radice)',grp:'verbi'},{k:'話',r:'hana',it:'parlare (radice)',grp:'verbi'},
  {k:'読',r:'yo',it:'leggere (radice)',grp:'verbi'},{k:'書',r:'ka',it:'scrivere (radice)',grp:'verbi'},
  {k:'聞',r:'ki',it:'ascoltare (radice)',grp:'verbi'},
  {k:'生',r:'sei',it:'vita / crudo',grp:'verbi'},{k:'先',r:'saki',it:'prima / punta',grp:'verbi'},
  {k:'出',r:'de',it:'uscire (radice)',grp:'verbi'},{k:'入',r:'hai',it:'entrare (radice)',grp:'verbi'},
  {k:'立',r:'ta',it:'stare in piedi (radice)',grp:'verbi'},{k:'休',r:'yasu',it:'riposare (radice)',grp:'verbi'},
  {k:'買',r:'ka',it:'comprare (radice)',grp:'verbi'},{k:'車',r:'kuruma',it:'macchina',grp:'luoghi'},
];

// ---------- CATEGORIE (etichette leggibili) ----------
var CATEGORY_LABELS = {
  saluti: 'Saluti e cortesia',
  numeri: 'Numeri e quantità',
  tempo: 'Tempo e giorni',
  cibo: 'Cibo e ristorante',
  direzioni: 'Direzioni e luoghi',
  trasporti: 'Trasporti',
  emergenza: 'Emergenze e salute',
  verbi: 'Verbi comuni',
  aggettivi: 'Aggettivi comuni',
  shopping: 'Shopping e soldi',
  smalltalk: 'Small talk e domande',
  alloggio: 'Alloggio',
  anime: 'Anime e manga',
  natura: 'Natura',
  persone: 'Persone e corpo',
  luoghi: 'Luoghi e direzioni',
  casa: 'Casa e famiglia',
  corpo: 'Corpo e benessere',
  meteo: 'Meteo',
  hobby: 'Hobby e tempo libero',
  colori: 'Colori',
  lavoroscuola: 'Lavoro e scuola',
};

// ---------- VOCABOLARIO (per SRS) ----------
var VOCAB = [
  // saluti
  {jp:'おはようございます',kana:'おはようございます',romaji:'ohayou gozaimasu',it:'buongiorno (mattina)',cat:'saluti'},
  {jp:'こんにちは',kana:'こんにちは',romaji:'konnichiwa',it:'buongiorno / salve',cat:'saluti'},
  {jp:'こんばんは',kana:'こんばんは',romaji:'konbanwa',it:'buonasera',cat:'saluti'},
  {jp:'さようなら',kana:'さようなら',romaji:'sayounara',it:'arrivederci',cat:'saluti'},
  {jp:'おやすみなさい',kana:'おやすみなさい',romaji:'oyasumi nasai',it:'buonanotte',cat:'saluti'},
  {jp:'ありがとうございます',kana:'ありがとうございます',romaji:'arigatou gozaimasu',it:'grazie',cat:'saluti'},
  {jp:'すみません',kana:'すみません',romaji:'sumimasen',it:'mi scusi / scusa',cat:'saluti'},
  {jp:'ごめんなさい',kana:'ごめんなさい',romaji:'gomen nasai',it:'mi dispiace',cat:'saluti'},
  {jp:'お願いします',kana:'おねがいします',romaji:'onegaishimasu',it:'per favore',cat:'saluti'},
  {jp:'どういたしまして',kana:'どういたしまして',romaji:'dou itashimashite',it:'prego (risposta a grazie)',cat:'saluti'},
  {jp:'はじめまして',kana:'はじめまして',romaji:'hajimemashite',it:'piacere (primo incontro)',cat:'saluti'},
  {jp:'よろしくお願いします',kana:'よろしくおねがいします',romaji:'yoroshiku onegaishimasu',it:'piacere / mi raccomando',cat:'saluti'},
  {jp:'はい',kana:'はい',romaji:'hai',it:'sì',cat:'saluti'},
  {jp:'いいえ',kana:'いいえ',romaji:'iie',it:'no',cat:'saluti'},
  {jp:'大丈夫です',kana:'だいじょうぶです',romaji:'daijoubu desu',it:'va bene / tutto ok',cat:'saluti'},

  // numeri
  {jp:'ゼロ',kana:'ゼロ',romaji:'zero',it:'zero',cat:'numeri'},
  {jp:'一',kana:'いち',romaji:'ichi',it:'uno (1)',cat:'numeri'},
  {jp:'二',kana:'に',romaji:'ni',it:'due (2)',cat:'numeri'},
  {jp:'三',kana:'さん',romaji:'san',it:'tre (3)',cat:'numeri'},
  {jp:'四',kana:'よん',romaji:'yon',it:'quattro (4)',cat:'numeri'},
  {jp:'五',kana:'ご',romaji:'go',it:'cinque (5)',cat:'numeri'},
  {jp:'六',kana:'ろく',romaji:'roku',it:'sei (6)',cat:'numeri'},
  {jp:'七',kana:'なな',romaji:'nana',it:'sette (7)',cat:'numeri'},
  {jp:'八',kana:'はち',romaji:'hachi',it:'otto (8)',cat:'numeri'},
  {jp:'九',kana:'きゅう',romaji:'kyuu',it:'nove (9)',cat:'numeri'},
  {jp:'十',kana:'じゅう',romaji:'juu',it:'dieci (10)',cat:'numeri'},
  {jp:'二十',kana:'にじゅう',romaji:'nijuu',it:'venti (20)',cat:'numeri'},
  {jp:'三十',kana:'さんじゅう',romaji:'sanjuu',it:'trenta (30)',cat:'numeri'},
  {jp:'百',kana:'ひゃく',romaji:'hyaku',it:'cento (100)',cat:'numeri'},
  {jp:'千',kana:'せん',romaji:'sen',it:'mille (1000)',cat:'numeri'},
  {jp:'万',kana:'まん',romaji:'man',it:'diecimila (10.000)',cat:'numeri'},
  {jp:'円',kana:'えん',romaji:'en',it:'yen (valuta)',cat:'numeri'},

  // tempo
  {jp:'今日',kana:'きょう',romaji:'kyou',it:'oggi',cat:'tempo'},
  {jp:'明日',kana:'あした',romaji:'ashita',it:'domani',cat:'tempo'},
  {jp:'昨日',kana:'きのう',romaji:'kinou',it:'ieri',cat:'tempo'},
  {jp:'今',kana:'いま',romaji:'ima',it:'adesso',cat:'tempo'},
  {jp:'朝',kana:'あさ',romaji:'asa',it:'mattina',cat:'tempo'},
  {jp:'昼',kana:'ひる',romaji:'hiru',it:'mezzogiorno / giorno',cat:'tempo'},
  {jp:'夜',kana:'よる',romaji:'yoru',it:'sera / notte',cat:'tempo'},
  {jp:'週末',kana:'しゅうまつ',romaji:'shuumatsu',it:'weekend',cat:'tempo'},
  {jp:'月曜日',kana:'げつようび',romaji:'getsuyoubi',it:'lunedì',cat:'tempo'},
  {jp:'火曜日',kana:'かようび',romaji:'kayoubi',it:'martedì',cat:'tempo'},
  {jp:'水曜日',kana:'すいようび',romaji:'suiyoubi',it:'mercoledì',cat:'tempo'},
  {jp:'木曜日',kana:'もくようび',romaji:'mokuyoubi',it:'giovedì',cat:'tempo'},
  {jp:'金曜日',kana:'きんようび',romaji:'kinyoubi',it:'venerdì',cat:'tempo'},
  {jp:'土曜日',kana:'どようび',romaji:'doyoubi',it:'sabato',cat:'tempo'},
  {jp:'日曜日',kana:'にちようび',romaji:'nichiyoubi',it:'domenica',cat:'tempo'},

  // cibo
  {jp:'ご飯',kana:'ごはん',romaji:'gohan',it:'riso / pasto',cat:'cibo'},
  {jp:'水',kana:'みず',romaji:'mizu',it:'acqua',cat:'cibo'},
  {jp:'お茶',kana:'おちゃ',romaji:'ocha',it:'tè',cat:'cibo'},
  {jp:'ビール',kana:'ビール',romaji:'biiru',it:'birra',cat:'cibo'},
  {jp:'美味しい',kana:'おいしい',romaji:'oishii',it:'buono (cibo)',cat:'cibo'},
  {jp:'辛い',kana:'からい',romaji:'karai',it:'piccante',cat:'cibo'},
  {jp:'甘い',kana:'あまい',romaji:'amai',it:'dolce',cat:'cibo'},
  {jp:'レストラン',kana:'レストラン',romaji:'resutoran',it:'ristorante',cat:'cibo'},
  {jp:'メニュー',kana:'メニュー',romaji:'menyuu',it:'menu',cat:'cibo'},
  {jp:'お会計',kana:'おかいけい',romaji:'okaikei',it:'il conto',cat:'cibo'},
  {jp:'魚',kana:'さかな',romaji:'sakana',it:'pesce',cat:'cibo'},
  {jp:'肉',kana:'にく',romaji:'niku',it:'carne',cat:'cibo'},
  {jp:'野菜',kana:'やさい',romaji:'yasai',it:'verdura',cat:'cibo'},
  {jp:'卵',kana:'たまご',romaji:'tamago',it:'uovo',cat:'cibo'},
  {jp:'麺',kana:'めん',romaji:'men',it:'noodles / pasta',cat:'cibo'},
  {jp:'箸',kana:'はし',romaji:'hashi',it:'bacchette',cat:'cibo'},
  {jp:'これ',kana:'これ',romaji:'kore',it:'questo',cat:'cibo'},
  {jp:'それ',kana:'それ',romaji:'sore',it:'quello (vicino a te)',cat:'cibo'},
  {jp:'ください',kana:'ください',romaji:'kudasai',it:'per favore (dammi)',cat:'cibo'},
  {jp:'いただきます',kana:'いただきます',romaji:'itadakimasu',it:'formula prima di mangiare',cat:'cibo'},
  {jp:'ごちそうさまでした',kana:'ごちそうさまでした',romaji:'gochisousama deshita',it:'formula dopo aver mangiato',cat:'cibo'},
  {jp:'ラーメン',kana:'ラーメン',romaji:'raamen',it:'ramen',cat:'cibo'},
  {jp:'寿司',kana:'すし',romaji:'sushi',it:'sushi',cat:'cibo'},
  {jp:'天ぷら',kana:'てんぷら',romaji:'tenpura',it:'tempura',cat:'cibo'},
  {jp:'デザート',kana:'デザート',romaji:'dezaato',it:'dessert',cat:'cibo'},
  {jp:'おかわり',kana:'おかわり',romaji:'okawari',it:'bis (di cibo/bevanda)',cat:'cibo'},

  // direzioni
  {jp:'駅',kana:'えき',romaji:'eki',it:'stazione',cat:'direzioni'},
  {jp:'空港',kana:'くうこう',romaji:'kuukou',it:'aeroporto',cat:'direzioni'},
  {jp:'トイレ',kana:'トイレ',romaji:'toire',it:'bagno',cat:'direzioni'},
  {jp:'病院',kana:'びょういん',romaji:'byouin',it:'ospedale',cat:'direzioni'},
  {jp:'薬局',kana:'やっきょく',romaji:'yakkyoku',it:'farmacia',cat:'direzioni'},
  {jp:'コンビニ',kana:'コンビニ',romaji:'konbini',it:'minimarket',cat:'direzioni'},
  {jp:'右',kana:'みぎ',romaji:'migi',it:'destra',cat:'direzioni'},
  {jp:'左',kana:'ひだり',romaji:'hidari',it:'sinistra',cat:'direzioni'},
  {jp:'まっすぐ',kana:'まっすぐ',romaji:'massugu',it:'dritto',cat:'direzioni'},
  {jp:'ここ',kana:'ここ',romaji:'koko',it:'qui',cat:'direzioni'},
  {jp:'どこ',kana:'どこ',romaji:'doko',it:'dove',cat:'direzioni'},
  {jp:'近い',kana:'ちかい',romaji:'chikai',it:'vicino',cat:'direzioni'},
  {jp:'遠い',kana:'とおい',romaji:'tooi',it:'lontano',cat:'direzioni'},
  {jp:'入口',kana:'いりぐち',romaji:'iriguchi',it:'entrata',cat:'direzioni'},
  {jp:'出口',kana:'でぐち',romaji:'deguchi',it:'uscita',cat:'direzioni'},
  {jp:'地図',kana:'ちず',romaji:'chizu',it:'mappa',cat:'direzioni'},
  {jp:'信号',kana:'しんごう',romaji:'shingou',it:'semaforo',cat:'direzioni'},

  // trasporti
  {jp:'電車',kana:'でんしゃ',romaji:'densha',it:'treno',cat:'trasporti'},
  {jp:'バス',kana:'バス',romaji:'basu',it:'autobus',cat:'trasporti'},
  {jp:'タクシー',kana:'タクシー',romaji:'takushii',it:'taxi',cat:'trasporti'},
  {jp:'切符',kana:'きっぷ',romaji:'kippu',it:'biglietto',cat:'trasporti'},
  {jp:'飛行機',kana:'ひこうき',romaji:'hikouki',it:'aereo',cat:'trasporti'},
  {jp:'乗り換え',kana:'のりかえ',romaji:'norikae',it:'cambio (treno)',cat:'trasporti'},
  {jp:'何時',kana:'なんじ',romaji:'nanji',it:'che ora',cat:'trasporti'},
  {jp:'時刻表',kana:'じこくひょう',romaji:'jikokuhyou',it:'orario',cat:'trasporti'},
  {jp:'自転車',kana:'じてんしゃ',romaji:'jitensha',it:'bicicletta',cat:'trasporti'},
  {jp:'車',kana:'くるま',romaji:'kuruma',it:'macchina',cat:'trasporti'},
  {jp:'道',kana:'みち',romaji:'michi',it:'strada',cat:'trasporti'},
  {jp:'橋',kana:'はし',romaji:'hashi',it:'ponte',cat:'trasporti'},
  {jp:'運転手',kana:'うんてんしゅ',romaji:'untenshu',it:'autista',cat:'trasporti'},
  {jp:'遅れる',kana:'おくれる',romaji:'okureru',it:'ritardare',cat:'trasporti'},
  {jp:'早い',kana:'はやい',romaji:'hayai',it:'veloce / presto',cat:'trasporti'},
  {jp:'新幹線',kana:'しんかんせん',romaji:'shinkansen',it:'treno superveloce',cat:'trasporti'},
  {jp:'ホーム',kana:'ホーム',romaji:'hoomu',it:'banchina',cat:'trasporti'},
  {jp:'改札',kana:'かいさつ',romaji:'kaisatsu',it:'tornelli / controllo biglietti',cat:'trasporti'},

  // emergenza
  {jp:'助けて',kana:'たすけて',romaji:'tasukete',it:'aiuto!',cat:'emergenza'},
  {jp:'危ない',kana:'あぶない',romaji:'abunai',it:'pericoloso / attento',cat:'emergenza'},
  {jp:'病気',kana:'びょうき',romaji:'byouki',it:'malattia',cat:'emergenza'},
  {jp:'痛い',kana:'いたい',romaji:'itai',it:'dolore / fa male',cat:'emergenza'},
  {jp:'熱',kana:'ねつ',romaji:'netsu',it:'febbre',cat:'emergenza'},
  {jp:'薬',kana:'くすり',romaji:'kusuri',it:'medicina',cat:'emergenza'},
  {jp:'警察',kana:'けいさつ',romaji:'keisatsu',it:'polizia',cat:'emergenza'},
  {jp:'救急車',kana:'きゅうきゅうしゃ',romaji:'kyuukyuusha',it:'ambulanza',cat:'emergenza'},
  {jp:'火事',kana:'かじ',romaji:'kaji',it:'incendio',cat:'emergenza'},
  {jp:'地震',kana:'じしん',romaji:'jishin',it:'terremoto',cat:'emergenza'},
  {jp:'アレルギー',kana:'アレルギー',romaji:'arerugii',it:'allergia',cat:'emergenza'},
  {jp:'医者',kana:'いしゃ',romaji:'isha',it:'dottore',cat:'emergenza'},
  {jp:'大丈夫ですか',kana:'だいじょうぶですか',romaji:'daijoubu desu ka',it:'stai bene?',cat:'emergenza'},
  {jp:'気をつけて',kana:'きをつけて',romaji:'ki wo tsukete',it:'stai attento',cat:'emergenza'},

  // verbi (forma dizionario)
  {jp:'食べる',kana:'たべる',romaji:'taberu',it:'mangiare',cat:'verbi'},
  {jp:'飲む',kana:'のむ',romaji:'nomu',it:'bere',cat:'verbi'},
  {jp:'行く',kana:'いく',romaji:'iku',it:'andare',cat:'verbi'},
  {jp:'来る',kana:'くる',romaji:'kuru',it:'venire',cat:'verbi'},
  {jp:'見る',kana:'みる',romaji:'miru',it:'vedere',cat:'verbi'},
  {jp:'聞く',kana:'きく',romaji:'kiku',it:'ascoltare / chiedere',cat:'verbi'},
  {jp:'話す',kana:'はなす',romaji:'hanasu',it:'parlare',cat:'verbi'},
  {jp:'分かる',kana:'わかる',romaji:'wakaru',it:'capire',cat:'verbi'},
  {jp:'買う',kana:'かう',romaji:'kau',it:'comprare',cat:'verbi'},
  {jp:'待つ',kana:'まつ',romaji:'matsu',it:'aspettare',cat:'verbi'},
  {jp:'帰る',kana:'かえる',romaji:'kaeru',it:'tornare',cat:'verbi'},
  {jp:'使う',kana:'つかう',romaji:'tsukau',it:'usare',cat:'verbi'},
  {jp:'座る',kana:'すわる',romaji:'suwaru',it:'sedersi',cat:'verbi'},
  {jp:'立つ',kana:'たつ',romaji:'tatsu',it:'alzarsi / stare in piedi',cat:'verbi'},
  {jp:'寝る',kana:'ねる',romaji:'neru',it:'dormire',cat:'verbi'},
  {jp:'起きる',kana:'おきる',romaji:'okiru',it:'svegliarsi',cat:'verbi'},
  {jp:'歩く',kana:'あるく',romaji:'aruku',it:'camminare',cat:'verbi'},
  {jp:'撮る',kana:'とる',romaji:'toru',it:'fotografare',cat:'verbi'},
  {jp:'探す',kana:'さがす',romaji:'sagasu',it:'cercare',cat:'verbi'},
  {jp:'持つ',kana:'もつ',romaji:'motsu',it:'portare / avere con sé',cat:'verbi'},

  // aggettivi
  {jp:'大きい',kana:'おおきい',romaji:'ookii',it:'grande',cat:'aggettivi'},
  {jp:'小さい',kana:'ちいさい',romaji:'chiisai',it:'piccolo',cat:'aggettivi'},
  {jp:'新しい',kana:'あたらしい',romaji:'atarashii',it:'nuovo',cat:'aggettivi'},
  {jp:'古い',kana:'ふるい',romaji:'furui',it:'vecchio',cat:'aggettivi'},
  {jp:'良い',kana:'いい',romaji:'ii',it:'buono',cat:'aggettivi'},
  {jp:'悪い',kana:'わるい',romaji:'warui',it:'cattivo',cat:'aggettivi'},
  {jp:'高い',kana:'たかい',romaji:'takai',it:'alto / caro',cat:'aggettivi'},
  {jp:'安い',kana:'やすい',romaji:'yasui',it:'economico',cat:'aggettivi'},
  {jp:'綺麗',kana:'きれい',romaji:'kirei',it:'bello / pulito',cat:'aggettivi'},
  {jp:'静か',kana:'しずか',romaji:'shizuka',it:'tranquillo',cat:'aggettivi'},

  // shopping
  {jp:'お金',kana:'おかね',romaji:'okane',it:'soldi',cat:'shopping'},
  {jp:'いくらですか',kana:'いくらですか',romaji:'ikura desu ka',it:'quanto costa?',cat:'shopping'},
  {jp:'高すぎる',kana:'たかすぎる',romaji:'takasugiru',it:'troppo caro',cat:'shopping'},
  {jp:'安くしてください',kana:'やすくしてください',romaji:'yasuku shite kudasai',it:'mi fa uno sconto?',cat:'shopping'},
  {jp:'現金',kana:'げんきん',romaji:'genkin',it:'contanti',cat:'shopping'},
  {jp:'カード',kana:'カード',romaji:'kaado',it:'carta (di pagamento)',cat:'shopping'},
  {jp:'お釣り',kana:'おつり',romaji:'otsuri',it:'resto',cat:'shopping'},
  {jp:'レジ',kana:'レジ',romaji:'reji',it:'cassa',cat:'shopping'},
  {jp:'店',kana:'みせ',romaji:'mise',it:'negozio',cat:'shopping'},
  {jp:'市場',kana:'いちば',romaji:'ichiba',it:'mercato',cat:'shopping'},

  // small talk
  {jp:'名前',kana:'なまえ',romaji:'namae',it:'nome',cat:'smalltalk'},
  {jp:'どこから来ましたか',kana:'どこからきましたか',romaji:'dokokara kimashita ka',it:'da dove vieni?',cat:'smalltalk'},
  {jp:'イタリアから来ました',kana:'イタリアからきました',romaji:'itaria kara kimashita',it:'vengo dall\'Italia',cat:'smalltalk'},
  {jp:'何歳ですか',kana:'なんさいですか',romaji:'nansai desu ka',it:'quanti anni hai?',cat:'smalltalk'},
  {jp:'仕事は何ですか',kana:'しごとはなんですか',romaji:'shigoto wa nan desu ka',it:'che lavoro fai?',cat:'smalltalk'},
  {jp:'分かりません',kana:'わかりません',romaji:'wakarimasen',it:'non capisco',cat:'smalltalk'},
  {jp:'もう一度お願いします',kana:'もういちどおねがいします',romaji:'mou ichido onegaishimasu',it:'può ripetere per favore?',cat:'smalltalk'},
  {jp:'ゆっくり話してください',kana:'ゆっくりはなしてください',romaji:'yukkuri hanashite kudasai',it:'parli più lentamente per favore',cat:'smalltalk'},
  {jp:'英語を話せますか',kana:'えいごをはなせますか',romaji:'eigo wo hanasemasu ka',it:'parla inglese?',cat:'smalltalk'},
  {jp:'日本語が少し話せます',kana:'にほんごがすこしはなせます',romaji:'nihongo ga sukoshi hanasemasu',it:'parlo un po\' di giapponese',cat:'smalltalk'},
  {jp:'写真を撮ってもいいですか',kana:'しゃしんをとってもいいですか',romaji:'shashin wo tottemo ii desu ka',it:'posso fare una foto?',cat:'smalltalk'},
  {jp:'トイレはどこですか',kana:'トイレはどこですか',romaji:'toire wa doko desu ka',it:'dov\'è il bagno?',cat:'smalltalk'},
  {jp:'Wi-Fiはありますか',kana:'ワイファイはありますか',romaji:'waifai wa arimasu ka',it:'c\'è il wifi?',cat:'smalltalk'},
  {jp:'楽しい',kana:'たのしい',romaji:'tanoshii',it:'divertente',cat:'smalltalk'},
  {jp:'大好きです',kana:'だいすきです',romaji:'daisuki desu',it:'mi piace molto',cat:'smalltalk'},

  // casa e famiglia
  {jp:'家族',kana:'かぞく',romaji:'kazoku',it:'famiglia',cat:'casa'},
  {jp:'父',kana:'ちち',romaji:'chichi',it:'padre (mio)',cat:'casa'},
  {jp:'母',kana:'はは',romaji:'haha',it:'madre (mia)',cat:'casa'},
  {jp:'兄弟',kana:'きょうだい',romaji:'kyoudai',it:'fratelli',cat:'casa'},
  {jp:'友達',kana:'ともだち',romaji:'tomodachi',it:'amico',cat:'casa'},
  {jp:'部屋',kana:'へや',romaji:'heya',it:'stanza',cat:'casa'},
  {jp:'布団',kana:'ふとん',romaji:'futon',it:'futon (materasso giapponese)',cat:'casa'},
  {jp:'風呂',kana:'ふろ',romaji:'furo',it:'bagno (vasca)',cat:'casa'},
  {jp:'台所',kana:'だいどころ',romaji:'daidokoro',it:'cucina',cat:'casa'},
  {jp:'玄関',kana:'げんかん',romaji:'genkan',it:'ingresso (dove si tolgono le scarpe)',cat:'casa'},
  {jp:'靴',kana:'くつ',romaji:'kutsu',it:'scarpe',cat:'casa'},
  {jp:'スリッパ',kana:'スリッパ',romaji:'surippa',it:'pantofole',cat:'casa'},
  {jp:'鍵',kana:'かぎ',romaji:'kagi',it:'chiave',cat:'casa'},
  {jp:'窓',kana:'まど',romaji:'mado',it:'finestra',cat:'casa'},
  {jp:'庭',kana:'にわ',romaji:'niwa',it:'giardino',cat:'casa'},

  // corpo e benessere
  {jp:'頭',kana:'あたま',romaji:'atama',it:'testa',cat:'corpo'},
  {jp:'お腹',kana:'おなか',romaji:'onaka',it:'pancia',cat:'corpo'},
  {jp:'喉',kana:'のど',romaji:'nodo',it:'gola',cat:'corpo'},
  {jp:'背中',kana:'せなか',romaji:'senaka',it:'schiena',cat:'corpo'},
  {jp:'足',kana:'あし',romaji:'ashi',it:'piede / gamba',cat:'corpo'},
  {jp:'腕',kana:'うで',romaji:'ude',it:'braccio',cat:'corpo'},
  {jp:'指',kana:'ゆび',romaji:'yubi',it:'dito',cat:'corpo'},
  {jp:'疲れた',kana:'つかれた',romaji:'tsukareta',it:'stanco',cat:'corpo'},
  {jp:'元気',kana:'げんき',romaji:'genki',it:'energico / stai bene',cat:'corpo'},
  {jp:'眠い',kana:'ねむい',romaji:'nemui',it:'assonnato',cat:'corpo'},

  // meteo
  {jp:'天気',kana:'てんき',romaji:'tenki',it:'tempo (meteo)',cat:'meteo'},
  {jp:'晴れ',kana:'はれ',romaji:'hare',it:'sereno',cat:'meteo'},
  {jp:'曇り',kana:'くもり',romaji:'kumori',it:'nuvoloso',cat:'meteo'},
  {jp:'雪',kana:'ゆき',romaji:'yuki',it:'neve',cat:'meteo'},
  {jp:'風',kana:'かぜ',romaji:'kaze',it:'vento',cat:'meteo'},
  {jp:'暑い',kana:'あつい',romaji:'atsui',it:'caldo',cat:'meteo'},
  {jp:'寒い',kana:'さむい',romaji:'samui',it:'freddo',cat:'meteo'},
  {jp:'涼しい',kana:'すずしい',romaji:'suzushii',it:'fresco',cat:'meteo'},
  {jp:'蒸し暑い',kana:'むしあつい',romaji:'mushiatsui',it:'afoso / umido',cat:'meteo'},

  // hobby e tempo libero
  {jp:'音楽',kana:'おんがく',romaji:'ongaku',it:'musica',cat:'hobby'},
  {jp:'映画',kana:'えいが',romaji:'eiga',it:'film',cat:'hobby'},
  {jp:'本',kana:'ほん',romaji:'hon',it:'libro',cat:'hobby'},
  {jp:'漫画',kana:'まんが',romaji:'manga',it:'fumetto',cat:'hobby'},
  {jp:'アニメ',kana:'アニメ',romaji:'anime',it:'anime',cat:'hobby'},
  {jp:'ゲーム',kana:'ゲーム',romaji:'geemu',it:'videogioco',cat:'hobby'},
  {jp:'写真',kana:'しゃしん',romaji:'shashin',it:'foto',cat:'hobby'},
  {jp:'旅行',kana:'りょこう',romaji:'ryokou',it:'viaggio',cat:'hobby'},
  {jp:'温泉',kana:'おんせん',romaji:'onsen',it:'terme',cat:'hobby'},
  {jp:'神社',kana:'じんじゃ',romaji:'jinja',it:'santuario shintoista',cat:'hobby'},
  {jp:'お寺',kana:'おてら',romaji:'otera',it:'tempio buddista',cat:'hobby'},

  // colori
  {jp:'赤',kana:'あか',romaji:'aka',it:'rosso',cat:'colori'},
  {jp:'青',kana:'あお',romaji:'ao',it:'blu',cat:'colori'},
  {jp:'白',kana:'しろ',romaji:'shiro',it:'bianco',cat:'colori'},
  {jp:'黒',kana:'くろ',romaji:'kuro',it:'nero',cat:'colori'},
  {jp:'緑',kana:'みどり',romaji:'midori',it:'verde',cat:'colori'},
  {jp:'黄色',kana:'きいろ',romaji:'kiiro',it:'giallo',cat:'colori'},

  // lavoro e scuola
  {jp:'仕事',kana:'しごと',romaji:'shigoto',it:'lavoro',cat:'lavoroscuola'},
  {jp:'学校',kana:'がっこう',romaji:'gakkou',it:'scuola',cat:'lavoroscuola'},
  {jp:'会社',kana:'かいしゃ',romaji:'kaisha',it:'azienda',cat:'lavoroscuola'},
  {jp:'先生',kana:'せんせい',romaji:'sensei',it:'insegnante / maestro',cat:'lavoroscuola'},
  {jp:'学生',kana:'がくせい',romaji:'gakusei',it:'studente',cat:'lavoroscuola'},
  {jp:'休み',kana:'やすみ',romaji:'yasumi',it:'vacanza / pausa',cat:'lavoroscuola'},
];

// ---------- FRASI (per shadowing / lettura) ----------
var PHRASES = [
  // direzioni
  {jp:'すみません、駅はどこですか。',romaji:'Sumimasen, eki wa doko desu ka.',it:'Scusi, dov\'è la stazione?',cat:'direzioni'},
  {jp:'まっすぐ行ってください。',romaji:'Massugu itte kudasai.',it:'Vada dritto, per favore.',cat:'direzioni'},
  {jp:'右に曲がってください。',romaji:'Migi ni magatte kudasai.',it:'Giri a destra, per favore.',cat:'direzioni'},
  {jp:'左に曲がってください。',romaji:'Hidari ni magatte kudasai.',it:'Giri a sinistra, per favore.',cat:'direzioni'},
  {jp:'どのくらいかかりますか。',romaji:'Dono kurai kakarimasu ka.',it:'Quanto tempo ci vuole?',cat:'direzioni'},
  {jp:'歩いて行けますか。',romaji:'Aruite ikemasu ka.',it:'Posso arrivarci a piedi?',cat:'direzioni'},
  {jp:'この地図で今どこにいますか。',romaji:'Kono chizu de ima doko ni imasu ka.',it:'Dove siamo ora su questa mappa?',cat:'direzioni'},
  {jp:'次の角を左です。',romaji:'Tsugi no kado wo hidari desu.',it:'Al prossimo angolo è a sinistra.',cat:'direzioni'},
  {jp:'歩いてどのくらいですか。',romaji:'Aruite dono kurai desu ka.',it:'Quanto ci vuole a piedi?',cat:'direzioni'},
  {jp:'案内所はどこですか。',romaji:'Annaijo wa doko desu ka.',it:'Dov\'è l\'ufficio informazioni?',cat:'direzioni'},

  // cibo
  {jp:'おすすめは何ですか。',romaji:'Osusume wa nan desu ka.',it:'Cosa consiglia?',cat:'cibo'},
  {jp:'これをください。',romaji:'Kore wo kudasai.',it:'Questo, per favore.',cat:'cibo'},
  {jp:'お水をください。',romaji:'Omizu wo kudasai.',it:'Acqua, per favore.',cat:'cibo'},
  {jp:'お会計をお願いします。',romaji:'Okaikei wo onegaishimasu.',it:'Il conto, per favore.',cat:'cibo'},
  {jp:'とても美味しかったです。',romaji:'Totemo oishikatta desu.',it:'Era molto buono.',cat:'cibo'},
  {jp:'辛くないものはありますか。',romaji:'Karakunai mono wa arimasu ka.',it:'C\'è qualcosa non piccante?',cat:'cibo'},
  {jp:'アレルギーがあります。',romaji:'Arerugii ga arimasu.',it:'Ho un\'allergia.',cat:'cibo'},
  {jp:'ベジタリアン料理はありますか。',romaji:'Bejitarian ryouri wa arimasu ka.',it:'C\'è un piatto vegetariano?',cat:'cibo'},
  {jp:'おすすめの地元料理は何ですか。',romaji:'Osusume no jimoto ryouri wa nan desu ka.',it:'Qual è il piatto tipico locale consigliato?',cat:'cibo'},
  {jp:'おかわりできますか。',romaji:'Okawari dekimasu ka.',it:'Posso avere un bis?',cat:'cibo'},
  {jp:'持ち帰りできますか。',romaji:'Mochikaeri dekimasu ka.',it:'Posso portarlo via?',cat:'cibo'},
  {jp:'量を少なくできますか。',romaji:'Ryou wo sukunaku dekimasu ka.',it:'Può farmi una porzione più piccola?',cat:'cibo'},
  {jp:'デザートは何がありますか。',romaji:'Dezaato wa nani ga arimasu ka.',it:'Cosa avete come dessert?',cat:'cibo'},
  {jp:'禁煙席をお願いします。',romaji:'Kin\'en seki wo onegaishimasu.',it:'Un tavolo non fumatori, per favore.',cat:'cibo'},

  // trasporti
  {jp:'この電車は東京駅に行きますか。',romaji:'Kono densha wa Toukyou eki ni ikimasu ka.',it:'Questo treno va alla stazione di Tokyo?',cat:'trasporti'},
  {jp:'切符はどこで買えますか。',romaji:'Kippu wa doko de kaemasu ka.',it:'Dove posso comprare il biglietto?',cat:'trasporti'},
  {jp:'次の電車は何時ですか。',romaji:'Tsugi no densha wa nanji desu ka.',it:'A che ora è il prossimo treno?',cat:'trasporti'},
  {jp:'タクシーを呼んでもらえますか。',romaji:'Takushii wo yonde moraemasu ka.',it:'Può chiamarmi un taxi?',cat:'trasporti'},
  {jp:'ここで降ります。',romaji:'Koko de orimasu.',it:'Scendo qui.',cat:'trasporti'},
  {jp:'新幹線のチケットはどこで買えますか。',romaji:'Shinkansen no chiketto wa doko de kaemasu ka.',it:'Dove compro il biglietto dello Shinkansen?',cat:'trasporti'},
  {jp:'このバスは市内中心部に行きますか。',romaji:'Kono basu wa shinai chuushinbu ni ikimasu ka.',it:'Questo bus va al centro città?',cat:'trasporti'},
  {jp:'終電は何時ですか。',romaji:'Shuuden wa nanji desu ka.',it:'A che ora è l\'ultimo treno?',cat:'trasporti'},
  {jp:'時刻表を見せてもらえますか。',romaji:'Jikokuhyou wo misete moraemasu ka.',it:'Posso vedere l\'orario?',cat:'trasporti'},

  // emergenza
  {jp:'助けてください。',romaji:'Tasukete kudasai.',it:'Aiuto, per favore.',cat:'emergenza'},
  {jp:'具合が悪いです。',romaji:'Guai ga warui desu.',it:'Non mi sento bene.',cat:'emergenza'},
  {jp:'病院はどこですか。',romaji:'Byouin wa doko desu ka.',it:'Dov\'è l\'ospedale?',cat:'emergenza'},
  {jp:'警察を呼んでください。',romaji:'Keisatsu wo yonde kudasai.',it:'Chiami la polizia, per favore.',cat:'emergenza'},
  {jp:'道に迷いました。',romaji:'Michi ni mayoimashita.',it:'Mi sono perso.',cat:'emergenza'},
  {jp:'パスポートをなくしました。',romaji:'Pasupooto wo nakushimashita.',it:'Ho perso il passaporto.',cat:'emergenza'},
  {jp:'一番近い病院はどこですか。',romaji:'Ichiban chikai byouin wa doko desu ka.',it:'Qual è l\'ospedale più vicino?',cat:'emergenza'},
  {jp:'保険に入っています。',romaji:'Hoken ni haitte imasu.',it:'Ho un\'assicurazione.',cat:'emergenza'},
  {jp:'薬局はまだ開いていますか。',romaji:'Yakkyoku wa mada aite imasu ka.',it:'La farmacia è ancora aperta?',cat:'emergenza'},
  {jp:'大使館はどこですか。',romaji:'Taishikan wa doko desu ka.',it:'Dov\'è l\'ambasciata?',cat:'emergenza'},

  // small talk
  {jp:'日本語は少ししか話せません。',romaji:'Nihongo wa sukoshi shika hanasemasen.',it:'Parlo solo un po\' di giapponese.',cat:'smalltalk'},
  {jp:'もう一度言ってください。',romaji:'Mou ichido itte kudasai.',it:'Lo ripeta, per favore.',cat:'smalltalk'},
  {jp:'ゆっくりお願いします。',romaji:'Yukkuri onegaishimasu.',it:'Più lentamente, per favore.',cat:'smalltalk'},
  {jp:'これは何ですか。',romaji:'Kore wa nan desu ka.',it:'Cos\'è questo?',cat:'smalltalk'},
  {jp:'写真を撮ってもいいですか。',romaji:'Shashin wo tottemo ii desu ka.',it:'Posso fare una foto?',cat:'smalltalk'},
  {jp:'とても親切ですね、ありがとうございます。',romaji:'Totemo shinsetsu desu ne, arigatou gozaimasu.',it:'È molto gentile, grazie.',cat:'smalltalk'},
  {jp:'お邪魔しました。',romaji:'Ojama shimashita.',it:'Scusi il disturbo (formula di commiato).',cat:'smalltalk'},
  {jp:'お世話になりました。',romaji:'Osewa ni narimashita.',it:'Grazie per l\'aiuto/l\'ospitalità (formula di commiato).',cat:'smalltalk'},
  {jp:'日本は初めてです。',romaji:'Nihon wa hajimete desu.',it:'È la mia prima volta in Giappone.',cat:'smalltalk'},
  {jp:'どのくらい滞在しますか。',romaji:'Dono kurai taizai shimasu ka.',it:'Quanto ti fermi?',cat:'smalltalk'},
  {jp:'一人で旅行していますか。',romaji:'Hitori de ryokou shite imasu ka.',it:'Stai viaggiando da solo?',cat:'smalltalk'},
  {jp:'とても美しい場所ですね。',romaji:'Totemo utsukushii basho desu ne.',it:'È un posto bellissimo.',cat:'smalltalk'},
  {jp:'また来たいです。',romaji:'Mata kitai desu.',it:'Vorrei tornare.',cat:'smalltalk'},
  {jp:'ここに住んでいますか。',romaji:'Koko ni sunde imasu ka.',it:'Vivi qui?',cat:'smalltalk'},

  // alloggio
  {jp:'チェックインをお願いします。',romaji:'Chekku in wo onegaishimasu.',it:'Vorrei fare il check-in.',cat:'alloggio'},
  {jp:'Wi-Fiのパスワードは何ですか。',romaji:'Waifai no pasuwaado wa nan desu ka.',it:'Qual è la password del wifi?',cat:'alloggio'},
  {jp:'タオルをもう一枚もらえますか。',romaji:'Taoru wo mou ichimai moraemasu ka.',it:'Posso avere un altro asciugamano?',cat:'alloggio'},
  {jp:'荷物を預けられますか。',romaji:'Nimotsu wo azukeraremasu ka.',it:'Posso lasciare i bagagli?',cat:'alloggio'},
  {jp:'布団の使い方を教えてください。',romaji:'Futon no tsukaikata wo oshiete kudasai.',it:'Mi spieghi come si usa il futon?',cat:'alloggio'},
  {jp:'何時までに帰ればいいですか。',romaji:'Nanji made ni kaereba ii desu ka.',it:'Entro che ora devo rientrare?',cat:'alloggio'},
  {jp:'温泉は何時から入れますか。',romaji:'Onsen wa nanji kara hairemasu ka.',it:'Da che ora si può entrare nell\'onsen?',cat:'alloggio'},

  // shopping
  {jp:'いくらですか。',romaji:'Ikura desu ka.',it:'Quanto costa?',cat:'shopping'},
  {jp:'カードは使えますか。',romaji:'Kaado wa tsukaemasu ka.',it:'Posso pagare con carta?',cat:'shopping'},
  {jp:'試着してもいいですか。',romaji:'Shichaku shitemo ii desu ka.',it:'Posso provarlo?',cat:'shopping'},
  {jp:'免税できますか。',romaji:'Menzei dekimasu ka.',it:'È possibile il tax-free?',cat:'shopping'},
  {jp:'サイズ違いはありますか。',romaji:'Saizu chigai wa arimasu ka.',it:'Avete un\'altra taglia?',cat:'shopping'},
  {jp:'ラッピングをお願いします。',romaji:'Rappingu wo onegaishimasu.',it:'Può incartarlo per favore?',cat:'shopping'},
  {jp:'これと同じものはありますか。',romaji:'Kore to onaji mono wa arimasu ka.',it:'Avete lo stesso articolo?',cat:'shopping'},

  // meteo
  {jp:'今日の天気はどうですか。',romaji:'Kyou no tenki wa dou desu ka.',it:'Com\'è il tempo oggi?',cat:'meteo'},
  {jp:'明日は雨が降りますか。',romaji:'Ashita wa ame ga furimasu ka.',it:'Domani pioverà?',cat:'meteo'},
  {jp:'とても暑いですね。',romaji:'Totemo atsui desu ne.',it:'Fa molto caldo, vero?',cat:'meteo'},
  {jp:'傘が必要ですか。',romaji:'Kasa ga hitsuyou desu ka.',it:'Serve l\'ombrello?',cat:'meteo'},
  {jp:'今は何度ですか。',romaji:'Ima wa nando desu ka.',it:'Quanti gradi ci sono ora?',cat:'meteo'},

  // lavoro e scuola
  {jp:'お仕事は何をしていますか。',romaji:'Oshigoto wa nani wo shite imasu ka.',it:'Che lavoro fai?',cat:'lavoroscuola'},
  {jp:'会社員です。',romaji:'Kaishain desu.',it:'Sono un impiegato.',cat:'lavoroscuola'},
  {jp:'日本語を勉強しています。',romaji:'Nihongo wo benkyou shite imasu.',it:'Sto studiando giapponese.',cat:'lavoroscuola'},
  {jp:'休みの日は何をしますか。',romaji:'Yasumi no hi wa nani wo shimasu ka.',it:'Cosa fai nei giorni liberi?',cat:'lavoroscuola'},
  {jp:'学校で日本語を習いました。',romaji:'Gakkou de nihongo wo naraimashita.',it:'Ho imparato il giapponese a scuola.',cat:'lavoroscuola'},

  // anime e manga — espressioni tipiche dello shounen, di uso generico
  {jp:'諦めない。',romaji:'Akiramenai.',it:'Non mi arrendo.',cat:'anime'},
  {jp:'まだまだだ。',romaji:'Mada mada da.',it:'Non è ancora finita.',cat:'anime'},
  {jp:'本気を出す時が来た。',romaji:'Honki wo dasu toki ga kita.',it:'È arrivato il momento di fare sul serio.',cat:'anime'},
  {jp:'絶対に負けない。',romaji:'Zettai ni makenai.',it:'Non perderò mai.',cat:'anime'},
  {jp:'仲間を守りたい。',romaji:'Nakama wo mamoritai.',it:'Voglio proteggere i miei compagni.',cat:'anime'},
  {jp:'夢を諦めるな。',romaji:'Yume wo akirameru na.',it:'Non abbandonare il tuo sogno.',cat:'anime'},
  {jp:'覚悟はいいか？',romaji:'Kakugo wa ii ka?',it:'Sei pronto (mentalmente)?',cat:'anime'},
  {jp:'心を燃やせ。',romaji:'Kokoro wo moyase.',it:'Fai ardere il tuo cuore.',cat:'anime'},
  {jp:'一緒に戦おう。',romaji:'Issho ni tatakaou.',it:'Combattiamo insieme.',cat:'anime'},
  {jp:'俺が守る。',romaji:'Ore ga mamoru.',it:'Sono io a proteggerti.',cat:'anime'},
  {jp:'負けるわけにはいかない。',romaji:'Makeru wake ni wa ikanai.',it:'Non posso permettermi di perdere.',cat:'anime'},
  {jp:'まだ終わっていない。',romaji:'Mada owatte inai.',it:'Non è ancora finita.',cat:'anime'},
  {jp:'全力を尽くす。',romaji:'Zenryoku wo tsukusu.',it:'Darò tutto me stesso.',cat:'anime'},
  {jp:'信じてる。',romaji:'Shinjiteru.',it:'Ci credo (ho fiducia).',cat:'anime'},
  {jp:'負けられない戦いがある。',romaji:'Makerarenai tatakai ga aru.',it:'C\'è una battaglia che non posso perdere.',cat:'anime'},
  {jp:'力を合わせよう。',romaji:'Chikara wo awaseyou.',it:'Uniamo le forze.',cat:'anime'},
  {jp:'これが俺のやり方だ。',romaji:'Kore ga ore no yarikata da.',it:'Questo è il mio modo di fare le cose.',cat:'anime'},
  {jp:'まだ見ぬ世界へ。',romaji:'Mada minu sekai e.',it:'Verso un mondo mai visto.',cat:'anime'},
  {jp:'夢は必ず叶う。',romaji:'Yume wa kanarazu kanau.',it:'I sogni si avverano sempre.',cat:'anime'},
  {jp:'一歩ずつ前へ進む。',romaji:'Ippo zutsu mae e susumu.',it:'Avanzo un passo alla volta.',cat:'anime'},
  {jp:'心配するな、俺がいる。',romaji:'Shinpai suru na, ore ga iru.',it:'Non preoccuparti, ci sono io.',cat:'anime'},
  {jp:'限界を超えろ。',romaji:'Genkai wo koero.',it:'Supera i tuoi limiti.',cat:'anime'},
];

// ---------- PIANO DI STUDIO ----------
var STUDY_PLAN = [
  {
    fase: 'Fase 1 — Fondamenta',
    start: '2026-07-17',
    end: '2026-07-30',
    obiettivi: [
      'Leggere hiragana e katakana a colpo d\'occhio (senza pensarci)',
      'Saluti e cortesia di base',
      'Capire il ritmo/pronuncia giapponese (le "more", non le sillabe italiane)'
    ]
  },
  {
    fase: 'Fase 2 — Corpo centrale',
    start: '2026-07-31',
    end: '2026-09-20',
    obiettivi: [
      '10-15 parole nuove al giorno via SRS (vocabolario ad alta frequenza)',
      'Primi kanji di base, letti attraverso le parole che già conosci',
      '10 min al giorno di shadowing su frasi facili',
      'Ascolto passivo regolare (podcast/NHK Easy Japanese)'
    ]
  },
  {
    fase: 'Fase 3 — Sopravvivenza rurale',
    start: '2026-09-21',
    end: '2026-10-18',
    obiettivi: [
      'Frasi pratiche per situazioni reali: indicazioni, trasporti, cibo, emergenze',
      'Small talk con locali dove l\'inglese non arriva',
      'Più ascolto a velocità naturale, più speaking attivo (shadowing a voce alta)'
    ]
  },
  {
    fase: 'Fase 4 — Consolidamento',
    start: '2026-10-19',
    end: '2026-11-02',
    obiettivi: [
      'Ripasso spaziato di tutto il materiale (le carte SRS più deboli)',
      'Conversazioni simulate (ripeti a voce alta le frasi come se parlassi con qualcuno)',
      'Phrasebook finale sempre pronto sul telefono'
    ]
  },
];
